<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>python_onnxruntime_cuda_vendor</name>
  <version>0.1.2</version>
  <description>Vendor package for the CUDA Python ONNX Runtime distribution.</description>

  <maintainer email="yuankunz@nvidia.com">Yuankun Zhu</maintainer>
  <license>Apache-2.0</license>
  <license>MIT</license>
  <author email="yuankunz@nvidia.com">Yuankun Zhu</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>onnxruntime_core_vendor</depend>
  <depend>onnxruntime_cuda_vendor</depend>
  <build_depend>python3-pip</build_depend>

  <exec_depend>python3-flatbuffers</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-packaging</exec_depend>
  <exec_depend>python3-protobuf</exec_depend>
  <exec_depend>python3</exec_depend>

  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_cmake_xmllint</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
