<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>qc_buffer_tutorial</name>
  <version>0.1.0</version>
  <description>Minimal publisher/subscriber tutorial for qc_buffer_backend
  intra-process HTP-CPU zero-copy.</description>

  <maintainer email="nasong@qti.qualcomm.com">Na Song</maintainer>
  <license>Apache-2.0</license>
  <author email="nasong@qti.qualcomm.com">Na Song</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>sensor_msgs</depend>
  <depend>rosidl_runtime_cpp</depend>
  <depend>qc_buffer</depend>

  <exec_depend>qc_buffer_backend</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
